### PR TITLE
Add mainfiles option, better defaults, descriptive messages

### PR DESCRIPTION
**Pull request by jesseditson**
- adds mainfiles option, which allows specification of the main file for packages without a bower.json
- defaults to all bower packages unless require.includes is specified (instead of only if require is missing)
- throw a more descriptive error message when unable to resolve a bower package

### CODE REVIEW

**Comment by tminglei** [comment]
Hi @jesseditson, sorry, I have submitted other changes before saw it.
Can you check and rework again?

**Comment by jesseditson** [comment]
Rebased and tested against my project, this one is ready for review again!

**Comment by tminglei** [comment]
Merged. _Thanks!_

**Comment by tminglei** [comment]
Hi @jesseditson, based on your codes, I did some code refactor and enhancement.
Pls check it.

**Comment by tminglei** [comment]
Hi @jesseditson, I published `browserify-bower v0.6.0`, which included your contributions.

Thanks again! :+1:

**Pull request merged**
